# Generated by Django 6.0 on 2026-01-02 21:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionsMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cm_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('track', models.CharField(max_length=255)),
                ('surface_type', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('track_condition', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=255)),
                ('weather', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('speed_recommendation', models.IntegerField()),
                ('stamina_recommendation', models.IntegerField()),
                ('power_recommendation', models.IntegerField()),
                ('guts_recommendation', models.IntegerField()),
                ('wit_recommendation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChampionsMeetingRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('income_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClubRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('income_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='support_cards/')),
                ('admin_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTrialsRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('income_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='umas/')),
                ('admin_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('banner_timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.bannertimeline')),
            ],
        ),
        migrations.CreateModel(
            name='BannerUma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('banner_timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.bannertimeline')),
            ],
        ),
        migrations.CreateModel(
            name='SupportsOnSupportBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('banner_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.bannersupport')),
                ('support_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.supportcard')),
            ],
        ),
        migrations.AddField(
            model_name='bannersupport',
            name='support_cards',
            field=models.ManyToManyField(related_name='support_banners', through='calculatorapi.SupportsOnSupportBanner', to='calculatorapi.supportcard'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('daily_carat', models.BooleanField(default=False)),
                ('current_carat', models.IntegerField(default=0)),
                ('uma_ticket', models.IntegerField(default=0)),
                ('support_ticket', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('champions_meeting_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculatorapi.championsmeetingrank')),
                ('club_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculatorapi.clubrank')),
                ('team_trials_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculatorapi.teamtrialsrank')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChampionsMeetingUmaRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champions_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.championsmeeting')),
                ('uma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.uma')),
            ],
        ),
        migrations.CreateModel(
            name='UmasOnUmaBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('banner_uma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.banneruma')),
                ('uma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.uma')),
            ],
        ),
        migrations.AddField(
            model_name='banneruma',
            name='umas',
            field=models.ManyToManyField(related_name='uma_banners', through='calculatorapi.UmasOnUmaBanner', to='calculatorapi.uma'),
        ),
        migrations.CreateModel(
            name='UserPlannedBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pulls', models.IntegerField()),
                ('banner_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.bannersupport')),
                ('banner_uma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.banneruma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('banner_support__isnull', False), ('banner_uma__isnull', True)), models.Q(('banner_support__isnull', True), ('banner_uma__isnull', False)), _connector='OR'), name='only_one_support_or_uma')],
            },
        ),
    ]
