# Generated by Django 6.0 on 2026-04-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='training_pass',
            field=models.BooleanField(default=False),
        ),
    ]
