# Generated by Django 6.0 on 2026-01-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannersupport',
            name='free_pulls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banneruma',
            name='free_pulls',
            field=models.IntegerField(default=0),
        ),
    ]
