# Generated by Django 6.0 on 2026-01-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0002_bannersupport_free_pulls_banneruma_free_pulls'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('carat_amount', models.IntegerField(default=0)),
                ('support_ticket_amount', models.IntegerField(default=0)),
                ('uma_ticket_amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
