# Generated by Django 6.0 on 2026-05-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0002_customuser_training_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueOfHeroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
