# Generated by Django 6.0 on 2026-01-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0003_eventrewards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventRewards',
            new_name='EventReward',
        ),
    ]
