# Generated by Django 6.0 on 2026-01-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0004_rename_eventrewards_eventreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championsmeeting',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='championsmeeting',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
