# Generated by Django 6.0 on 2026-01-12 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0005_alter_championsmeeting_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannersupport',
            name='banner_timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_banners', to='calculatorapi.bannertimeline'),
        ),
        migrations.AlterField(
            model_name='bannersupport',
            name='support_cards',
            field=models.ManyToManyField(through='calculatorapi.SupportsOnSupportBanner', to='calculatorapi.supportcard'),
        ),
        migrations.AlterField(
            model_name='banneruma',
            name='banner_timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uma_banners', to='calculatorapi.bannertimeline'),
        ),
        migrations.AlterField(
            model_name='banneruma',
            name='umas',
            field=models.ManyToManyField(through='calculatorapi.UmasOnUmaBanner', to='calculatorapi.uma'),
        ),
    ]
