# Generated by Django 6.0 on 2026-05-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0007_missing_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='championsmeetingrank',
            name='sr_shard_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='championsmeetingrank',
            name='ssr_shard_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='championsmeetingrank',
            name='support_ticket_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='championsmeetingrank',
            name='uma_ticket_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leagueofheroesrank',
            name='sr_shard_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leagueofheroesrank',
            name='ssr_shard_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leagueofheroesrank',
            name='support_ticket_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leagueofheroesrank',
            name='uma_ticket_amount',
            field=models.IntegerField(default=0),
        ),
    ]
