# Generated by Django 6.0 on 2026-05-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0010_patch_eventreward_shard_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreward',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
