# Generated by Django 6.0 on 2026-05-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0011_patch_eventreward_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannertimeline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_timelines/'),
        ),
        migrations.AlterField(
            model_name='championsmeeting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='champions_meetings/'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_events/'),
        ),
        migrations.AlterField(
            model_name='leagueofheroes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='league_of_heroes/'),
        ),
        migrations.AlterField(
            model_name='supportcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='support_cards/'),
        ),
        migrations.AlterField(
            model_name='uma',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='umas/'),
        ),
    ]
