# Generated by Django 6.0 on 2026-07-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0012_alter_bannertimeline_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannersupport',
            options={'verbose_name': 'support card banner', 'verbose_name_plural': 'support card banners'},
        ),
        migrations.AlterModelOptions(
            name='banneruma',
            options={'verbose_name': 'uma banner', 'verbose_name_plural': 'uma banners'},
        ),
        migrations.AlterModelOptions(
            name='championsmeeting',
            options={'verbose_name': 'Champions Meeting', 'verbose_name_plural': 'Champions Meetings'},
        ),
        migrations.AlterModelOptions(
            name='championsmeetingrank',
            options={'verbose_name': 'Champions Meeting rank', 'verbose_name_plural': 'Champions Meeting ranks'},
        ),
        migrations.AlterModelOptions(
            name='championsmeetingumarecommendation',
            options={'verbose_name': 'recommended uma', 'verbose_name_plural': 'recommended umas'},
        ),
        migrations.AlterModelOptions(
            name='leagueofheroes',
            options={'verbose_name': 'League of Heroes event', 'verbose_name_plural': 'League of Heroes events'},
        ),
        migrations.AlterModelOptions(
            name='leagueofheroesrank',
            options={'verbose_name': 'League of Heroes rank', 'verbose_name_plural': 'League of Heroes ranks'},
        ),
        migrations.AlterModelOptions(
            name='supportsonsupportbanner',
            options={'verbose_name': 'support card on banner', 'verbose_name_plural': 'support cards on banner'},
        ),
        migrations.AlterModelOptions(
            name='umasonumabanner',
            options={'verbose_name': 'uma on banner', 'verbose_name_plural': 'umas on banner'},
        ),
        migrations.AlterField(
            model_name='bannersupport',
            name='admin_comments',
            field=models.TextField(blank=True, help_text='Notes for editors.', null=True),
        ),
        migrations.AlterField(
            model_name='bannersupport',
            name='free_pulls',
            field=models.IntegerField(default=0, help_text='Free pulls players get on this banner — the calculator counts these toward affordability.'),
        ),
        migrations.AlterField(
            model_name='banneruma',
            name='admin_comments',
            field=models.TextField(blank=True, help_text='Notes for editors.', null=True),
        ),
        migrations.AlterField(
            model_name='banneruma',
            name='free_pulls',
            field=models.IntegerField(default=0, help_text='Free pulls players get on this banner — the calculator counts these toward affordability.'),
        ),
        migrations.AlterField(
            model_name='championsmeeting',
            name='cm_number',
            field=models.IntegerField(verbose_name='meeting number'),
        ),
        migrations.AlterField(
            model_name='supportcard',
            name='admin_comments',
            field=models.TextField(blank=True, help_text='Notes for editors.', null=True),
        ),
        migrations.AlterField(
            model_name='supportsonsupportbanner',
            name='recommendation',
            field=models.TextField(blank=True, help_text='Optional recommendation text for this card on this banner.', null=True),
        ),
        migrations.AlterField(
            model_name='uma',
            name='admin_comments',
            field=models.TextField(blank=True, help_text='Notes for editors.', null=True),
        ),
        migrations.AlterField(
            model_name='umasonumabanner',
            name='recommendation',
            field=models.TextField(blank=True, help_text='Optional recommendation text for this uma on this banner.', null=True),
        ),
    ]
