# Generated by Django 6.0 on 2026-07-17 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0016_remove_old_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Changelog Entry',
                'verbose_name_plural': 'Changelog Entries',
            },
        ),
        migrations.CreateModel(
            name='ChangelogChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('added', 'Added'), ('fixed', 'Fixed'), ('changed', 'Changed')], default='changed', max_length=10)),
                ('text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='calculatorapi.changelogentry')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
