# Generated by Django 6.0 on 2026-07-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0020_remove_cm_loh_old_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcard',
            name='game_id',
            field=models.PositiveIntegerField(blank=True, help_text="Numeric card id from the reference game data (e.g. 30024). Anchors this card's image filename in the DO Space.", null=True, unique=True),
        ),
    ]
