# Generated by Django 6.0 on 2026-07-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds the banner_timeline FK to GameEvent (nullable — not every event ties
    to a banner). start_date/end_date are loosened to nullable here too, as a
    transitional safety net until 0023 backfills banner_timeline and 0024
    removes these columns entirely once dates are derived from the linked
    banner instead.
    """

    dependencies = [
        ('calculatorapi', '0021_supportcard_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='banner_timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_events', to='calculatorapi.bannertimeline'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
