# Generated by Django 6.0 on 2026-07-21 19:27

from django.db import migrations


class Migration(migrations.Migration):
    """Removes the old start_date/end_date columns now that 0023 has linked
    every resolvable GameEvent to its BannerTimeline -- dates are derived
    entirely from that FK from here on (see calculatorapi/predictions.py)."""

    dependencies = [
        ('calculatorapi', '0023_backfill_gameevent_banner_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameevent',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='gameevent',
            name='start_date',
        ),
    ]
