# Generated by Django 6.0 on 2026-07-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0024_remove_gameevent_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='carat_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='carats_throughout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='sr_crystal_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='sr_shard_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='ssr_crystal_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='ssr_shard_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='support_ticket_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='uma_ticket_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='EventReward',
        ),
    ]
