# Generated by Django 6.0 on 2026-07-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0025_gameevent_carat_amount_gameevent_carats_throughout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='misc_earnings',
            field=models.BooleanField(default=True),
        ),
    ]
