# Generated by Django 6.0 on 2026-07-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0026_customuser_misc_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discounted_paid_pulls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_price_paid_pulls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_shop_tickets',
            field=models.BooleanField(default=False),
        ),
    ]
