# Generated by Django 6.0 on 2026-07-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0027_customuser_discounted_paid_pulls_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championsmeetingrank',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Champions Meeting rank', 'verbose_name_plural': 'Champions Meeting ranks'},
        ),
        migrations.AddField(
            model_name='championsmeetingrank',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
