# Generated by Django 6.0 on 2026-08-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0029_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannertimeline',
            name='schedule_offset_days',
            field=models.IntegerField(blank=True, default=0, help_text='Days to push this and every later date forward. Leave at 0 unless global has slipped its schedule. Ignored once global dates are confirmed.', verbose_name='schedule offset (days)'),
        ),
        migrations.AddField(
            model_name='championsmeeting',
            name='schedule_offset_days',
            field=models.IntegerField(blank=True, default=0, help_text='Days to push this and every later date forward. Leave at 0 unless global has slipped its schedule. Ignored once global dates are confirmed.', verbose_name='schedule offset (days)'),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='schedule_offset_days',
            field=models.IntegerField(blank=True, default=0, help_text='Days to push this and every later date forward. Leave at 0 unless global has slipped its schedule. Ignored once global dates are confirmed.', verbose_name='schedule offset (days)'),
        ),
    ]
