# Generated by Django 6.0 on 2026-08-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0030_bannertimeline_schedule_offset_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueofheroes',
            name='direction',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='distance',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='guts_recommendation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='length',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='loh_number',
            field=models.IntegerField(default=0, verbose_name='league number'),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='power_recommendation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='season',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='speed_recommendation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='stamina_recommendation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='surface_type',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='track',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='track_condition',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='weather',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AddField(
            model_name='leagueofheroes',
            name='wit_recommendation',
            field=models.IntegerField(default=0),
        ),
    ]
