# Generated by Django 6.0 on 2026-08-06 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0032_backfill_leagueofheroes_loh_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnniversaryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('anniversary', 'Anniversary'), ('new_year', 'New Year'), ('campaign', 'Campaign')], default='anniversary', help_text="Drives the timeline strip's label and styling.", max_length=20)),
                ('jp_cutoff_date', models.DateField(blank=True, help_text='Selectors from this campaign can only pick cards released on JP on or before this date. Leave blank for no restriction.', null=True, verbose_name='JP cutoff date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='anniversary_events/')),
                ('accent_label', models.CharField(blank=True, help_text="Optional short badge text for the timeline strip, e.g. 'Guaranteed SSR'.", max_length=60)),
            ],
            options={
                'verbose_name': 'anniversary event',
                'verbose_name_plural': 'anniversary events',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='include_purchases_in_projection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='support_selector_ticket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uma_selector_ticket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='webstore_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplannedbanner',
            name='reserved_copies',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AnniversaryEventBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField(default=1, help_text="The sheet's Part number within this campaign (1, 2, 3, ...).")),
                ('anniversary_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_links', to='calculatorapi.anniversaryevent')),
                ('banner_timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anniversary_links', to='calculatorapi.bannertimeline')),
            ],
            options={
                'verbose_name': 'campaign banner part',
                'verbose_name_plural': 'campaign banner parts',
                'ordering': ['part_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='anniversaryevent',
            name='banner_timelines',
            field=models.ManyToManyField(blank=True, related_name='anniversary_events', through='calculatorapi.AnniversaryEventBanner', to='calculatorapi.bannertimeline'),
        ),
        migrations.CreateModel(
            name='AnniversaryEventProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('carat_pack', 'Carat pack'), ('uma_selector', 'Uma selector'), ('support_selector', 'Support selector')], default='carat_pack', max_length=20)),
                ('name', models.CharField(help_text="As shown to the user, e.g. '7500 Carat Pack' or '$21 Uma Selector'.", max_length=255)),
                ('usd_cost', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('paid_carat_amount', models.IntegerField(default=0, help_text='Paid carats granted per unit, before any webstore bonus.')),
                ('webstore_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Carat multiplier when bought via the webstore. 1.00 = no bonus.', max_digits=3)),
                ('max_quantity', models.PositiveIntegerField(default=1, help_text='Purchase limit for this campaign. Selectors are normally 1.')),
                ('jp_cutoff_date', models.DateField(blank=True, help_text="Leave blank to inherit the campaign's cutoff.", null=True, verbose_name='JP cutoff date override')),
                ('order', models.PositiveIntegerField(default=0)),
                ('anniversary_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='calculatorapi.anniversaryevent')),
            ],
            options={
                'verbose_name': 'campaign product',
                'verbose_name_plural': 'campaign products',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserPlannedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.anniversaryeventproduct')),
                ('target_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculatorapi.supportcard')),
                ('target_uma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculatorapi.uma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'planned purchase',
                'verbose_name_plural': 'planned purchases',
            },
        ),
        migrations.AddConstraint(
            model_name='anniversaryeventbanner',
            constraint=models.UniqueConstraint(fields=('anniversary_event', 'banner_timeline'), name='unique_anniversary_event_banner'),
        ),
        migrations.AddConstraint(
            model_name='userplannedpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('target_uma__isnull', True), ('target_support__isnull', True), _connector='OR'), name='at_most_one_selector_target'),
        ),
    ]
