# Generated by Django 6.0 on 2026-08-11 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0034_backfill_anniversary_jp_cutoff_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationConstants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_base_carats', models.IntegerField(default=75, help_text='Carats from daily quests, every day. Sheet: the 75 in AN42.', validators=[django.core.validators.MinValueValidator(0)])),
                ('weekly_bonus_carats', models.IntegerField(default=150, help_text="TOTAL login bonus carats per week, spread evenly across the seven days rather than paid on specific ones. Sheet: the 150 in AN42's 75 + 150/7.", validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_carat_pack_per_day', models.IntegerField(default=50, help_text='Daily Carat Pack drip, credited as FREE carats. Sheet: AR42.', validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_carat_pack_paid_carats', models.IntegerField(default=500, help_text='Daily Carat Pack repurchase bonus, credited as PAID carats — the balance that funds discounted pulls. Sheet: AZ42.', validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_carat_pack_cycle_days', models.IntegerField(default=30, help_text='Days between Daily Carat Pack repurchases.', validators=[django.core.validators.MinValueValidator(1)])),
                ('training_pass_start_date', models.DateField(default='2027-08-15', help_text='The date the Training Pass feature launches on Global. Nothing is earned from it before this.')),
                ('training_pass_monthly_free_carats', models.IntegerField(default=1850, help_text="FREE half of the paid Training Pass's monthly carats. With the paid half below this totals the pass's headline figure. Sheet: AQ42.", validators=[django.core.validators.MinValueValidator(0)])),
                ('training_pass_monthly_paid_carats', models.IntegerField(default=350, help_text="PAID half of the paid Training Pass's monthly carats. Sheet: BA42.", validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_base_reward', models.IntegerField(default=500, help_text='Monthly carats for an account WITHOUT the paid Training Pass. Replaced by the paid figures above, never added to them.', validators=[django.core.validators.MinValueValidator(0)])),
                ('training_pass_free_uma_tickets', models.IntegerField(default=2, help_text='Monthly uma tickets every account gets once the pass launches.', validators=[django.core.validators.MinValueValidator(0)])),
                ('training_pass_free_support_tickets', models.IntegerField(default=2, help_text='Monthly support tickets every account gets once the pass launches.', validators=[django.core.validators.MinValueValidator(0)])),
                ('training_pass_paid_bonus_uma_tickets', models.IntegerField(default=2, help_text="EXTRA monthly uma tickets from the paid pass, added to the free tier's.", validators=[django.core.validators.MinValueValidator(0)])),
                ('training_pass_paid_bonus_support_tickets', models.IntegerField(default=2, help_text="EXTRA monthly support tickets from the paid pass, added to the free tier's.", validators=[django.core.validators.MinValueValidator(0)])),
                ('misc_earnings_monthly', models.IntegerField(default=3000, help_text='Monthly approximation of gifts, career and Team Trials extras, dripped daily as monthly/30. Toggled per user. Sheet: Timeline!AW1.', validators=[django.core.validators.MinValueValidator(0)])),
                ('misc_earnings_delay_days', models.IntegerField(default=30, help_text='Ramp-in before misc earnings start, counted from today. Sheet: AV42.', validators=[django.core.validators.MinValueValidator(0)])),
                ('fifty_day_login_carats', models.IntegerField(default=150, help_text='Carats per completed login-campaign cycle. Sheet: AU42.', validators=[django.core.validators.MinValueValidator(0)])),
                ('fifty_day_login_cycle_days', models.IntegerField(default=50, help_text='Length of that login campaign cycle, in days.', validators=[django.core.validators.MinValueValidator(1)])),
                ('valentines_carats', models.IntegerField(default=500, help_text="Valentine's Day gift. Universal — no toggle.", validators=[django.core.validators.MinValueValidator(0)])),
                ('valentines_month', models.IntegerField(default=2, help_text="Month of the Valentine's gift, 1-12.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('valentines_day', models.IntegerField(default=14, help_text="Day of month of the Valentine's gift.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('white_day_carats', models.IntegerField(default=500, help_text='White Day gift. Universal — no toggle.', validators=[django.core.validators.MinValueValidator(0)])),
                ('white_day_month', models.IntegerField(default=3, help_text='Month of the White Day gift, 1-12.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('white_day_day', models.IntegerField(default=14, help_text='Day of month of the White Day gift.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('monthly_shop_uma_tickets', models.IntegerField(default=4, help_text='Uma tickets in the monthly shop bundle. Off by default per user.', validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_shop_support_tickets', models.IntegerField(default=4, help_text='Support tickets in the monthly shop bundle.', validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_shop_restock_day', models.IntegerField(default=2, help_text='Day of month the shop restocks. Counting from here rather than the 1st stops a banner ending on the 1st being credited a bundle the player cannot buy yet. Sheet: BG42.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('pull_cost_carats', models.IntegerField(default=150, help_text='Carats per full-price pull.', validators=[django.core.validators.MinValueValidator(1)])),
                ('discounted_pull_cost_carats', models.IntegerField(default=50, help_text="Carats per discounted pull. PAID carats only, and capped at one per day of a banner's run.", validators=[django.core.validators.MinValueValidator(1)])),
                ('shards_per_crystal', models.IntegerField(default=20, help_text='Shards that combine into one uncap crystal.', validators=[django.core.validators.MinValueValidator(1)])),
                ('throughout_end_offset_days', models.IntegerField(default=4, help_text="Days trimmed off a banner's end before the decay curve is measured. Sheet: end_date - ('Carat Calculator'!G25 + 1).", validators=[django.core.validators.MinValueValidator(0)])),
                ('throughout_filter_grace_days', models.IntegerField(default=4, help_text="Grace window deciding which banners can still reach an event's throughout carats. Sheet: AQ32, which reads 3 — ours was fitted to 4 against published per-banner figures, so one of the offsets above may be absorbing a day. Confirm with the parity harness before treating either as authoritative.", validators=[django.core.validators.MinValueValidator(0)])),
                ('throughout_decay_k', models.DecimalField(decimal_places=2, default='2.00', help_text="Steepness of the curve's early exponential leg. Higher front-loads more of the pool into the first days of a banner.", max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('throughout_decay_linear_slope', models.DecimalField(decimal_places=2, default='0.80', help_text="Slope of the curve's slower linear leg, which governs the tail.", max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('prediction_factor', models.DecimalField(decimal_places=3, default='0.664', help_text="Global covers JP's back catalogue faster than real time; each day of JP gap maps to this many days of Global gap. Raising it pushes every unconfirmed banner LATER. Retune if the observed cadence shifts.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('game_event_end_buffer_days', models.IntegerField(default=4, help_text="Days a game event's end trails its linked banner's end by. Used both to date events and to recover the banner window the decay curve runs over.", validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'calculation constants',
                'verbose_name_plural': 'calculation constants',
            },
        ),
    ]
