# Generated by Django 6.0 on 2026-08-11 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0035_calculationconstants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationconstants',
            name='misc_earnings_monthly',
            field=models.IntegerField(default=1800, help_text="Monthly approximation of gifts, career and Team Trials extras, dripped daily as monthly/30. Toggled per user. KNOWN GAP: the sheet's own figure (Timeline!AW1) is 3000, i.e. 100 a day against our 60. This default preserves current behaviour; raising it is a deliberate parity change to make once the harness can measure the effect.", validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
