# Generated by Django 6.0 on 2026-08-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0036_alter_calculationconstants_misc_earnings_monthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannertimeline',
            name='banner_category',
            field=models.CharField(choices=[('standard', 'Standard'), ('race_prep_support', 'Race prep support rerun'), ('golden_week_revival', 'Golden Week revival'), ('rerun', 'Rerun')], default='standard', help_text="What kind of banner window this is. Drives the timeline card's layout and the category filter. Leave as Standard unless this is a revival, a rerun, or a race-prep support batch.", max_length=32),
        ),
    ]
