# Generated by Django 6.0 on 2026-08-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0037_bannertimeline_banner_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Visit',
                'verbose_name_plural': 'Daily Visits',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyVisitorHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('visitor_hash', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Daily Visitor Hash',
                'verbose_name_plural': 'Daily Visitor Hashes',
                'constraints': [models.UniqueConstraint(fields=('date', 'visitor_hash'), name='unique_visitor_hash_per_day')],
            },
        ),
    ]
