# Generated by Django 6.0 on 2026-08-18 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0038_dailyvisit_monthlyvisit_visitorhash'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerStepUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="As shown on the planner, e.g. '5th Anniversary SSR Select Step-Up'.", max_length=255)),
                ('card_type', models.CharField(choices=[('uma', '★3 Uma'), ('support', 'SSR Support')], default='support', help_text='Which pool this step-up draws from. Drives the odds labels.', max_length=10)),
                ('banner_count', models.PositiveIntegerField(default=1, help_text='How many banners of this card type the campaign sells. This is the hard ceiling on steps: banner_count x 5.', validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='step_up_banners/')),
                ('admin_comments', models.TextField(blank=True, help_text='Notes for editors.', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order within a campaign, e.g. to put ★3 before SSR.')),
            ],
            options={
                'verbose_name': 'step-up banner',
                'verbose_name_plural': 'step-up banners',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='userplannedbanner',
            name='only_one_support_or_uma',
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='step_up_cost_step_1',
            field=models.IntegerField(default=500, help_text='Paid carats for step 1 of a Select Step-Up ladder. Sheet: AL360.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='step_up_cost_step_2',
            field=models.IntegerField(default=700, help_text='Paid carats for step 2.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='step_up_cost_step_3',
            field=models.IntegerField(default=1000, help_text='Paid carats for step 3 (first guaranteed card).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='step_up_cost_step_4',
            field=models.IntegerField(default=1300, help_text='Paid carats for step 4 (second guaranteed card).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='step_up_cost_step_5',
            field=models.IntegerField(default=1500, help_text='Paid carats for step 5, where the player CHOOSES the guaranteed card. The five together total 5,000 for one completed banner.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='step_up_max_rounds',
            field=models.IntegerField(default=7, help_text="Safety bound on completed ladders, NOT the live constraint. Real cost and odds clamp at a banner's own banner_count x 5, which is always lower. The source sheet's 35-step cap is an artifact of its lookup table's extent rather than a game rule.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='step_up_pulls_per_step',
            field=models.IntegerField(default=10, help_text='Pulls per step. Each step is a 10-pull.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='step_up_target_rate',
            field=models.DecimalField(decimal_places=4, default='0.0030', help_text="Per-pull chance of the ONE card the player is chasing. Derived: the game's ~3% total ★3/SSR rate spread across the 10 cards they selected. Change it only if the pool size or the headline rate changes — it is not an independent dial.", max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='bannerstepup',
            name='anniversary_event',
            field=models.ForeignKey(help_text='The campaign selling it. Supplies the JP cutoff for candidates.', on_delete=django.db.models.deletion.CASCADE, related_name='step_up_banners', to='calculatorapi.anniversaryevent'),
        ),
        migrations.AddField(
            model_name='bannerstepup',
            name='banner_timeline',
            field=models.ForeignKey(help_text='The campaign part this step-up runs alongside — normally Part 2. Supplies the dates the projection uses.', on_delete=django.db.models.deletion.CASCADE, related_name='step_up_banners', to='calculatorapi.bannertimeline'),
        ),
        migrations.AddField(
            model_name='userplannedbanner',
            name='banner_step_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.bannerstepup'),
        ),
        migrations.AddConstraint(
            model_name='userplannedbanner',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('banner_step_up__isnull', True), ('banner_support__isnull', True), ('banner_uma__isnull', False)), models.Q(('banner_step_up__isnull', True), ('banner_support__isnull', False), ('banner_uma__isnull', True)), models.Q(('banner_step_up__isnull', False), ('banner_support__isnull', True), ('banner_uma__isnull', True)), _connector='OR'), name='exactly_one_banner_target'),
        ),
    ]
