# Generated by Django 6.0 on 2026-08-19 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0039_bannerstepup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStepUpSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveIntegerField(help_text='Which of the 10 selection slots, 1-based.')),
                ('is_target', models.BooleanField(default=False, help_text='The step 5 pick -- the copy the player chooses outright.')),
                ('banner_step_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='calculatorapi.bannerstepup')),
                ('support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.supportcard')),
                ('uma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.uma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'step-up selection',
                'verbose_name_plural': 'step-up selections',
                'ordering': ['banner_step_up', 'slot'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('support__isnull', True), ('uma__isnull', False)), models.Q(('support__isnull', False), ('uma__isnull', True)), _connector='OR'), name='exactly_one_selection_card'), models.UniqueConstraint(fields=('user', 'banner_step_up', 'slot'), name='unique_step_up_selection_slot'), models.UniqueConstraint(condition=models.Q(('is_target', True)), fields=('user', 'banner_step_up'), name='one_step_up_target_per_banner')],
            },
        ),
    ]
