# Generated by Django 6.0 on 2026-08-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0040_userstepupselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scenarios/')),
                ('banner_timeline', models.ForeignKey(blank=True, help_text='The banner this scenario launches alongside — supplies its start date. A scenario has no end date.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='calculatorapi.bannertimeline')),
            ],
            options={
                'verbose_name': 'scenario',
                'verbose_name_plural': 'scenarios',
            },
        ),
    ]
