# Generated by Django 6.0 on 2026-08-27 20:47

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0042_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatreonTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first on the site. Ties fall back to name.')),
            ],
            options={
                'verbose_name': 'Patreon Tier',
                'verbose_name_plural': 'Patreon Tiers',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PatreonSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='The name to thank them by. Use their Patreon handle, never a billing name.', max_length=100)),
                ('is_public', models.BooleanField(default=False, help_text='Off by default. While off they are counted anonymously instead. Only tick this for a name they chose to be shown by.', verbose_name='Show name publicly')),
                ('is_active', models.BooleanField(default=True, help_text='Untick when a pledge lapses. Keeps the row instead of deleting it.')),
                ('patron_since', models.DateField(blank=True, help_text='Optional. Used only to order supporters within a tier, longest-standing first.', null=True)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporters', to='calculatorapi.patreontier')),
            ],
            options={
                'verbose_name': 'Patreon Supporter',
                'verbose_name_plural': 'Patreon Supporters',
                'ordering': ('tier__order', models.OrderBy(models.F('patron_since'), nulls_last=True), 'display_name'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('display_name'), name='unique_patreon_supporter_display_name')],
            },
        ),
    ]
