# Generated by Django 6.0 on 2026-08-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0043_patreontier_patreonsupporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatreonCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, default='', help_text='Current Patreon access token. Rotated automatically; do not edit.', max_length=255)),
                ('refresh_token', models.CharField(blank=True, default='', help_text='Used to mint the next access token. Single-use — rotated on every refresh.', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the current access token stops working.', null=True)),
                ('campaign_id', models.CharField(blank=True, default='', help_text='Resolved from the API on first use and cached here.', max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time a sync completed and wrote changes.', null=True)),
                ('last_sync_error', models.TextField(blank=True, default='', help_text='Message from the last failed sync. Cleared when one succeeds.')),
            ],
            options={
                'verbose_name': 'Patreon credentials',
                'verbose_name_plural': 'Patreon credentials',
            },
        ),
    ]
