# Generated by Django 6.0 on 2026-08-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0044_patreoncredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='discounted_paid_pulls',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='monthly_shop_tickets',
            field=models.BooleanField(default=True),
        ),
    ]
