# Generated by Django 6.0 on 2026-09-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0045_alter_customuser_discounted_paid_pulls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogentry',
            name='key',
            field=models.SlugField(blank=True, help_text='Leave blank. A key means this entry is written in the repository (calculatorapi/data/changelog.yaml) and edits made here are replaced on the next deploy — edit the file instead.', max_length=100, null=True, unique=True),
        ),
    ]
