# Generated by Django 6.0 on 2026-09-02 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0046_changelogentry_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationconstants',
            name='training_pass_paid_ssr_shards',
            field=models.IntegerField(default=1, help_text="Monthly SSR uncap shards from an ACTIVE paid Training Pass. The free tier earns none, so unlike the tickets above there is no free counterpart to add this to. Delivered on the same monthly clock as the pass's carats and tickets.", validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
