# Generated by Django 6.0 on 2026-09-02 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0047_calculationconstants_training_pass_paid_ssr_shards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationconstants',
            name='misc_earnings_monthly',
            field=models.IntegerField(default=1800, help_text="Monthly approximation of gifts, career and Team Trials extras, dripped daily as monthly/30. Toggled per user. The live value is 2700 (90 a day), set here in the admin; this field default is only what a fresh database starts from. For reference the source sheet's own figure (Timeline!AW1) is 3000.", validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
