# Generated by Django 6.0 on 2026-09-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0048_alter_calculationconstants_misc_earnings_monthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='patreonsupporter',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Admin only — never shown on the website. Used to tell supporters with similar or changed display names apart.', max_length=254),
        ),
    ]
