# Generated by Django 6.0 on 2026-09-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0049_patreonsupporter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('discord', 'Discord'), ('patreon', 'Patreon')], max_length=20),
        ),
    ]
