# Generated by Django 6.0 on 2026-09-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0049_patreonsupporter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='uma',
            name='is_three_star',
            field=models.BooleanField(default=True, help_text='Uncheck for ★1/★2 units. Selectors and step-ups only grant ★3 umas, so anything unchecked here is hidden from the pickers.', verbose_name='Is ★3'),
        ),
        migrations.AddField(
            model_name='uma',
            name='is_time_limited',
            field=models.BooleanField(default=False, help_text='Only obtainable during a limited window, so selector tickets and step-ups can never take them. Hides this uma from every selector picker and stops a selector funding a banner it is featured on.'),
        ),
    ]
