# Generated by Django 6.0 on 2026-09-08 19:23

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0050_alter_socialaccount_provider'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patreonsupporter',
            name='unique_patreon_supporter_display_name',
        ),
        migrations.AddField(
            model_name='patreonsupporter',
            name='linked_user',
            field=models.OneToOneField(blank=True, help_text='The site account this patron signed in with, if they have linked one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patreon_supporter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patreonsupporter',
            name='patreon_user_id',
            field=models.CharField(blank=True, default='', help_text="Admin only — never shown on the website. Patreon's own id for this person; filled by the API sync and used to match them to a site account.", max_length=64),
        ),
        migrations.AddConstraint(
            model_name='patreonsupporter',
            constraint=models.UniqueConstraint(condition=models.Q(('patreon_user_id', ''), _negated=True), fields=('patreon_user_id',), name='unique_patreon_supporter_patreon_user_id'),
        ),
        migrations.AddConstraint(
            model_name='patreonsupporter',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('display_name'), condition=models.Q(('patreon_user_id', '')), name='unique_patreon_supporter_display_name'),
        ),
    ]
