# Generated by Django 6.0 on 2026-09-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0050_uma_is_three_star_uma_is_time_limited'),
        ('calculatorapi', '0051_patreon_supporter_account_link'),
    ]

    operations = [
    ]
