# Generated by Django 6.0 on 2026-09-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0052_merge_patreon_link_and_uma_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannersupport',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text="Tick when this banner is exceptionally worth pulling on. Highlights it on the Timeline and in the calculator's banner dropdown.", verbose_name='recommended'),
        ),
        migrations.AddField(
            model_name='banneruma',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text="Tick when this banner is exceptionally worth pulling on. Highlights it on the Timeline and in the calculator's banner dropdown.", verbose_name='recommended'),
        ),
        migrations.AddField(
            model_name='supportcard',
            name='purpose',
            field=models.CharField(blank=True, default='', help_text='Shown publicly when a player hovers this card\'s art on the Timeline, e.g. "Great for front runners." Leave blank to show nothing. Notes for other editors go in Admin comments instead.', max_length=100),
        ),
        migrations.AddField(
            model_name='uma',
            name='purpose',
            field=models.CharField(blank=True, default='', help_text='Shown publicly when a player hovers this uma\'s art on the Timeline, e.g. "Great pace parent." Leave blank to show nothing. Notes for other editors go in Admin comments instead.', max_length=100),
        ),
    ]
