"""Factory for read-only rank ViewSets — all four rank models share the same shape."""
from rest_framework import viewsets, serializers, permissions
from calculatorapi.models import (
    ClubRank,
    TeamTrialsRank,
    ChampionsMeetingRank,
    LeagueOfHeroesRank,
)

_RANK_FIELDS = ("id", "name", "income_amount")
# CM and LoH ranks also award tickets and shards per event.
_COMPETITIVE_RANK_FIELDS = (
    "id", "name", "income_amount",
    "uma_ticket_amount", "support_ticket_amount",
    "ssr_shard_amount", "sr_shard_amount",
)


def _make_rank_serializer(model, fields=_RANK_FIELDS):
    """Return a ModelSerializer class for the given rank model.

    Uses type() to build the Meta class before the serializer class so that
    DRF's metaclass sees a fully-configured Meta at class-creation time.
    """
    meta = type("Meta", (), {"model": model, "fields": fields})
    return type(
        f"{model.__name__}Serializer",
        (serializers.ModelSerializer,),
        {"Meta": meta},
    )


def _make_rank_viewset(model, serializer_class):
    """Return a ReadOnlyModelViewSet for the given rank model."""
    class _ViewSet(  # pylint: disable=too-many-ancestors,too-few-public-methods
        viewsets.ReadOnlyModelViewSet
    ):
        """Read-only ViewSet generated by _make_rank_viewset."""
        queryset = model.objects.all().order_by("income_amount")
        # Pure reference data — readable by guests.
        permission_classes = [permissions.AllowAny]

    _ViewSet.serializer_class = serializer_class
    _ViewSet.__name__ = f"{model.__name__}ViewSet"
    return _ViewSet


ClubRankSerializer = _make_rank_serializer(ClubRank)
TeamTrialsRankSerializer = _make_rank_serializer(TeamTrialsRank)
ChampionsMeetingRankSerializer = _make_rank_serializer(ChampionsMeetingRank, _COMPETITIVE_RANK_FIELDS)
LeagueOfHeroesRankSerializer = _make_rank_serializer(LeagueOfHeroesRank, _COMPETITIVE_RANK_FIELDS)

ClubRankViewSet = _make_rank_viewset(ClubRank, ClubRankSerializer)
TeamTrialsRankViewSet = _make_rank_viewset(TeamTrialsRank, TeamTrialsRankSerializer)
ChampionsMeetingRankViewSet = _make_rank_viewset(
    ChampionsMeetingRank, ChampionsMeetingRankSerializer
)
LeagueOfHeroesRankViewSet = _make_rank_viewset(
    LeagueOfHeroesRank, LeagueOfHeroesRankSerializer
)
