name: calculator-capstone
region: nyc

alerts:
  - rule: DEPLOYMENT_FAILED

features:
  - buildpack-stack=ubuntu-22

services:
  - name: api
    github:
      repo: charlesmerriman/calculatorproject
      branch: master
      deploy_on_push: true
    source_dir: /
    environment_slug: python
    instance_size_slug: apps-s-1vcpu-1gb
    instance_count: 1
    run_command: gunicorn --worker-tmp-dir /dev/shm calculatorproject.wsgi:application --bind 0.0.0.0:8080
    http_port: 8080
    envs:
      - key: DJANGO_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: "changeme-set-this-in-dashboard"
      - key: DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        scope: RUN_AND_BUILD_TIME
        value: "${APP_DOMAIN}"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: "https://calculator-capstone-uqax7.ondigitalocean.app"
      - key: CORS_ORIGIN_WHITELIST
        scope: RUN_AND_BUILD_TIME
        value: "https://${APP_DOMAIN}"
      - key: DEVELOPMENT_MODE
        scope: RUN_AND_BUILD_TIME
        value: "False"
      - key: DISABLE_COLLECTSTATIC 
        scope: BUILD_TIME
        value: "1"

jobs:
  - name: migrate
    kind: PRE_DEPLOY
    github:
      repo: charlesmerriman/calculatorproject
      branch: master
      deploy_on_push: true
    source_dir: /
    environment_slug: python
    instance_size_slug: apps-s-1vcpu-1gb
    run_command: python manage.py migrate --no-input && python manage.py collectstatic --no-input
    envs:
      - key: DJANGO_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: "changeme-set-this-in-dashboard"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "${db.DATABASE_URL}"
      - key: DEVELOPMENT_MODE
        scope: RUN_TIME
        value: "False"

static_sites:
  - name: frontend
    github:
      repo: charlesmerriman/calculatorcapstoneclient
      branch: master
      deploy_on_push: true
    source_dir: /
    build_command: npm run build
    output_dir: /dist
    environment_slug: node-js
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: "https://${APP_DOMAIN}"

databases:
  - name: db
    engine: PG
    version: "16"
    production: false

ingress:
  rules:
    - component:
        name: api
      match:
        path:
          prefix: /admin
    - component:
        name: api
      match:
        path:
          prefix: /login
    - component:
        name: api
      match:
        path:
          prefix: /register
    - component:
        name: api
      match:
        path:
          prefix: /logout
    - component:
        name: api
      match:
        path:
          prefix: /calculator-data
    - component:
        name: api
      match:
        path:
          prefix: /media
    - component:
        name: frontend
      match:
        path:
          prefix: /